<?php
$this->layout()->setLayout('admin/admin');
$this->title = "Editando Usuário";
$this->headTitle($this->title);
$this->selectedMenu = 'usuários';

?>

	<!--  start page-heading -->
	<div id="page-heading">
		<h1>Editando Usuário </h1>
	</div>
	<!-- end page-heading -->
	
	<table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
		<tr>
			<th rowspan="3" class="sized"><img src="<?= APPLICATION_URL ?>images/shared/side_shadowleft.jpg" width="20" height="300" alt="" /></th>
			<th class="topleft"></th>
			<td id="tbl-border-top">&nbsp;</td>
			<th class="topright"></th>
			<th rowspan="3" class="sized"><img src="<?= APPLICATION_URL ?>images/shared/side_shadowright.jpg" width="20" height="300" alt="" /></th>
		</tr>
		<tr>
			<td id="tbl-border-left"></td>
			<td>
				<!--  start content-table-inner -->
				<div id="content-table-inner">
				
					<table border="0" width="100%" cellpadding="0" cellspacing="0">
						<tr valign="top">
							<td>
								<?= $this->userForm ?>
							</td>
						</tr>
					</table>
				</div>
			</td>
		</tr>
	</table>