<?php
$this->layout()->setLayout('admin/admin');
$this->title = "Usuários";
$this->headTitle($this->title);
$this->selectedMenu = 'usuários';

//Javascripts
$this->headScript()->prependScript("
	$(function(){
		$('input').checkBox();
		
		$('.ui-checkbox').css({'cursor':'pointer'});
		
		$('#toggle-all').click(function() {
		 	$('#toggle-all').toggleClass('toggle-checked');
			$('#mainform input[type=checkbox]').checkBox('toggle');
			return false;
		});
	});
");

$this->checkboxScriptHelper();

echo $this->tableHelper($this->tableConfig, $this->paginator);