	<!--  start page-heading -->
	<div id="page-heading">
		<h1>Usuários</h1>
	</div>
	<!-- end page-heading -->

	<table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
	<tr>
		<th rowspan="3" class="sized"><img src="<?= APPLICATION_URL ?>images/shared/side_shadowleft.jpg" width="20" height="300" alt="" /></th>
		<th class="topleft"></th>
		<td id="tbl-border-top">&nbsp;</td>
		<th class="topright"></th>
		<th rowspan="3" class="sized"><img src="<?= APPLICATION_URL ?>images/shared/side_shadowright.jpg" width="20" height="300" alt="" /></th>
	</tr>
	<tr>
		<td id="tbl-border-left"></td>
		<td>
		<!--  start content-table-inner ...................................................................... START -->
		<div id="content-table-inner">
		
			<!--  start table-content  -->
			<div id="table-content">
		 
				<!--  start product-table ..................................................................................... -->
				<form id="mainform" action="">
				<table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
				<tr>
					<th class="table-header-check"><a id="toggle-all" ></a> </th>
					
					<?php foreach ( $this->columns as $key => $item ): ?>
					<th class="table-header-repeat line-left">
						<a <?php if($this->orderCol == $key){echo 'class="'.$this->orderType.'-order"';} ?> href="
						<?php
						$order = 'asc';
						
						if ( $this->orderCol == $key ) {
							if ( $this->orderType == 'asc' ) {
								$order = 'desc';
							} else {
								$order = 'asc';
							}
						}
						
						$urlOptions = array(
										'module' => $this->url['module'],
										'controller' => $this->url['controller'],
										'action' => 'index',
										'order' => $key.'-'.$order
						);

						echo $this->url($urlOptions)
						?>"><?= $item['title'] ?></a>
					</th>
					<?php endforeach; ?>
					
					<th class="table-header-options line-left"><a href="">Opções</a></th>
				</tr>
				
				<?php foreach($this->paginator as $key => $item): ?>
				<?php if ($key%2 == 0): ?><tr><?php else: ?><tr class="alternate-row"><?php endif; ?>
					<td><input  type="checkbox"/></td>
					
					<?php
					foreach($this->columns as $colKey => $colItem) {
						if ( isset($colItem['field'])) {
							$value = $item[ $colItem['field'] ];
						} else {
							$value = $item[ $this->mapper->getField( $colKey ) ];
						}

						if ( isset($colItem['filter']) ) {
							$value = $colItem['filter']($value);
							
						}
					?>
					<td><?= $value ?></td>
					<?php } ?>
					
					<td class="options-width">
					<a href="<?= $this->url(array(
							'module' => $this->url['module'],
							'controller' => $this->url['controller'], 
							'action'=> 'edit',
							'id' => $item[  $this->mapper->getField( $this->url['id'] ) ]
						)) ?>" title="Editar" class="icon-1 info-tooltip"></a>
					<a href="<?= $this->url(array(
							'module' => $this->url['module'],
							'controller' => $this->url['controller'],
							'action'=> 'delete',
							'id' => $item[  $this->mapper->getField( $this->url['id'] ) ]
						)) ?>" title="Deletar" class="icon-2 info-tooltip"></a>
					
					<!-- 
					<a href="" title="Edit" class="icon-3 info-tooltip"></a>
					<a href="" title="Edit" class="icon-4 info-tooltip"></a>
					<a href="" title="Edit" class="icon-5 info-tooltip"></a>
					-->
					</td>
				</tr>
				<?php endforeach; ?>

				</table>
				<!--  end product-table................................... --> 
				</form>
			</div>
			<!--  end content-table  -->
		
			<!--  start actions-box ............................................... -->
			<div id="actions-box">
				<a href="" class="action-slider"></a>
				<div id="actions-box-slider">
					<a href="" class="action-edit">Edit</a>
					<a href="" class="action-delete">Delete</a>
				</div>
				<div class="clear"></div>
			</div>
			<!-- end actions-box........... -->
			
			<!--  start paging..................................................... -->
			<?php if($this->paginator) {
				echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
			<!--  end paging................ -->
			
			<div class="clear"></div>
		 
		</div>
		<!--  end content-table-inner ............................................END  -->
		</td>
		<td id="tbl-border-right"></td>
	</tr>
	<tr>
		<th class="sized bottomleft"></th>
		<td id="tbl-border-bottom">&nbsp;</td>
		<th class="sized bottomright"></th>
	</tr>
	</table>
	<div class="clear">&nbsp;</div>
