<?= $this->render('header.phtml') ?>

		<?php
			//Stylesheet
			$this->screenStylesheetHelper();
		
			//Javascripts
			$this->pNGFixHelper();
			$this->loginReadyScriptHelper();
			
			$this->headScript()->prependScript("
				$(document).ready(function() {
					$('.styledselect').selectbox({ inputClass: 'selectbox_styled' });
					$('.styledselect_form_1').selectbox({ inputClass: 'styledselect_form_1' });
					$('.styledselect_form_2').selectbox({ inputClass: 'styledselect_form_2' });
					$('.styledselect_pages').selectbox({ inputClass: 'styledselect_pages' });
				});
			");
						
			$this->selectBoxV1Helper();
			$this->selectBoxV2Helper();
			$this->selectBoxV1Helper();
			
			//$this->sHA1Helper();
			$this->jQueryHelper();
		?>
		
		<!-- Start: stylesheets -->
		<?= $this->headLink() ?>
		
		<!-- End: stylesheets -->
		
		<!-- Start: javascripts -->
		<?= $this->headScript() ?>
		
		<!-- End: javascripts -->
		
	</head>
	<body>
		<?= $this->render('admin/page-top-outer.phtml') ?>
		
		<div class="clear">&nbsp;</div>
		
		<?= $this->render('admin/nav-outer-repeat.phtml') ?>
		
		<div class="clear"></div>
		
		<!-- start content-outer ........................................................................................................................START -->
		<div id="content-outer">
			<!-- start content -->
			<div id="content">
			
				<?= $this->layout()->content ?>
				
			</div>
			<!--  end content -->
		<div class="clear">&nbsp;</div>
		</div>
		<!--  end content-outer........................................................END -->

		<div class="clear">&nbsp;</div>
		
		<?= $this->render('admin/footer.phtml') ?>

<?= $this->render('footer.phtml') ?>